### ISSUE TITLE
Have a virtual class in place to interface with timechart.plot

### ISSUE THREAD

**Issue by cdc-mgz4** [reichlab/d3-foresight#14]
Passing a JSON parsed object of the dump from flusight throws errors. Probably missing some code to manipulate the data.

**Comment by lepisma** [comment]
Yes, that JSON file has everything needed for the complete application and not just the currently plotted view.

Based on the selected season, region and other variables, a transformed subset of this data is passed to the view components. These transformations are defined in [here](https://github.com/reichlab/flusight/blob/test-foresight/src/store/getters.js). More clearly, these transformed data variables are the arguments in functions like plot.
