### ISSUE TITLE
Document timechart.plot API in detail

### ISSUE THREAD

**Issue by cdc-mgz4** [reichlab/d3-foresight#16]
The names for the data parameters are not clear and the code is not easy to read. I need you to document all the required parameters in detail. This has to be done ASAP and it is to be completed before other programming task.

**Comment by lepisma** [comment]
See if 99fb6f4dc2ad58b92401806742a985d73d4cdd27 helps

**Comment by cdc-mgz4** [comment]
It contains what I need. Closing this for now. Issues about this document can be adressed later.
