### ISSUE TITLE
Allow custom x-axis and disentangle mmwr-weeks

### ISSUE THREAD

**Issue by lepisma** [reichlab/d3-foresight#3]

**Comment by cdc-mgz4** [comment]
I think MMRweeks can stay I've already set the biggest two libraries as external: Moment and d3. I think the bundle is down to an acceptable size.

**Comment by lepisma** [comment]
mmwr-weeks is used in a sense that the axis and the expected series are assumed to work on week numbers, more specifically mmwr weeks. A better way is to just let the user provide this information about
- series ticks, and
- their mapping to real time
since we are using two x axes and many of the forecast situations might need separate granularity of time (biweeks, days, etc.)
