### ISSUE TITLE
Bundle necessary style

### ISSUE THREAD

**Issue by lepisma** [reichlab/d3-foresight#4]
Make tooltip identifiers more specific and pull in the default styles from flusight inside the class instantiation process.

**Comment by cdc-mgz4** [comment]
I don't think this is a good Idea. The bundle can include a minimal CSS file for this by prefixing all rules with something. Correct me if wrong but you can require css when using webpack, right?\
By prefixing the CSS I mean:
```CSS
.d3-flusight .red {
  color: red;
}
```
By doing this we can keep style from the classes while keeping it self contained.

**Comment by lepisma** [comment]
Yup, I meant that only. Keeping class initialization process *handle* the div creation and styling process. The implementation will definitely keep them separate.

**Comment by lepisma** [comment]
This is mostly fixed. A few components left are covered in issue #8. Closing this.
