### ISSUE TITLE
clickable arrows on legend aren't displaying appropriately

### ISSUE THREAD

**Issue by nickreich** [reichlab/d3-foresight#45]
I see boxes instead of arrows. See image below:
![image](https://user-images.githubusercontent.com/1280767/37928081-b3f9b5be-3109-11e8-91c4-d4ed75efc7a9.png)

**Comment by lepisma** [comment]
Can you check if they work now?

**Comment by nickreich** [comment]
Nope, I still see empty boxes.

**Comment by lepisma** [comment]
This is working fine iirc.
