### ISSUE TITLE
Pass in marker presence as optional config object to constructors

### ISSUE THREAD

**Issue by lepisma** [reichlab/d3-foresight#7]
Markers showing things like onset could be made optional.

**Comment by cdc-mgz4** [comment]
I'm not what the markers are exactly. Could you add a screenshot?

**Comment by lepisma** [comment]
Yes, markers are classes in `src/markers`. For example, there is a marker `actual` which translates to actual line (line and dots). This is low priority, but if we don't want to, say, show a baseline, an optional config could allow that.
